
CREATE DATABASE videosFav;

use videosFav;

CREATE TABLE video (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(100) NOT NULL,
  category VARCHAR(15)
);

ALTER TABLE video ADD date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;


